// Authored: Albert Lane | Documented: Claude Sonnet 4.6 | 2026-06-27
// Canonical design token set — MacroHard 3D Standard v1
// Source of truth: design-tokens.json (root). Do not edit this file directly.

export const DESIGN_TOKENS = {
  _meta: {
    version: '1.0.0',
    authored: 'Albert Lane',
    documented: 'Claude Sonnet 4.6',
    date: '2026-06-12',
    standard: 'MacroHard 3D Design Standard v1',
    sec_ref: '17684-273-411-436',
  },
  colors: {
    sovereign: {
      primary:   '#0A1628',
      secondary: '#1E3A5F',
      accent:    '#00D4FF',
      warning:   '#FF6B35',
      success:   '#00C896',
      danger:    '#FF3860',
      surface:   '#0D1F3C',
      'surface-2': '#162944',
      text:      '#E8F4FD',
      'text-dim': '#7BA7CC',
      border:    '#1E3A5F',
    },
    '3d-standard': {
      'depth-0':  '#0A1628',
      'depth-1':  '#0D1F3C',
      'depth-2':  '#162944',
      'depth-3':  '#1E3A5F',
      'light-top':  '#00D4FF',
      'light-side': '#007A99',
      shadow:     '#040B14',
    },
  },
  typography: {
    'font-family': {
      mono:    "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
      sans:    "'Inter', 'Segoe UI', system-ui, sans-serif",
      display: "'Space Grotesk', 'Inter', sans-serif",
    },
    'font-size': {
      xs: '11px', sm: '13px', base: '15px', md: '17px',
      lg: '21px', xl: '26px', '2xl': '32px', '3xl': '42px',
    },
    'font-weight': { normal: 400, medium: 500, semibold: 600, bold: 700 },
    'line-height': { tight: 1.2, normal: 1.5, loose: 1.75 },
  },
  spacing: {
    '0': '0px',  '1': '4px',  '2': '8px',  '3': '12px',
    '4': '16px', '5': '20px', '6': '24px', '8': '32px',
    '10': '40px', '12': '48px', '16': '64px', '20': '80px', '24': '96px',
  },
  'border-radius': {
    none: '0px', sm: '3px', md: '6px', lg: '10px', xl: '16px', full: '9999px',
  },
  shadows: {
    sm: '0 1px 3px rgba(0,0,0,0.4)',
    md: '0 4px 12px rgba(0,0,0,0.5)',
    lg: '0 8px 24px rgba(0,0,0,0.6)',
    '3d': '4px 4px 0px #040B14, 8px 8px 0px rgba(4,11,20,0.5)',
  },
  '3d-standard': {
    'isometric-angle-x':    30,
    'isometric-angle-y':    30,
    'elevation-scale':      3,
    'shadow-offset-x':      4,
    'shadow-offset-y':      4,
    'highlight-intensity':  0.85,
    'ambient-intensity':    0.35,
  },
} as const;
